### ISSUE TITLE
miner start/restart not working

### ISSUE THREAD

**Issue by gl00m** [minershive/hiveos-asic#1]
Antminer D3 (Blissz beta) Я понимаю, что прошивка не поддерживается, но при небольшом изменении скриптов, все работает.
Суть проблемы: cgminer запускается через start-stop-daemon, причем запускается не сам cgminer, а screen который уже запускает cgminer. Если в этот момент уже есть запущеный screen (а он есть, это agent-screen), то start-stop-daemon думает, что процесс уже запущен и дабы предотвратить параллельный запуск, не запускает cgminer. 
Не важно как это делать miner start/restart или даже /etc/init.d/cgminer
Процесс который смущает s-s-daemon это "screen -x -S agent" если его убить, то все ок... И если отсоедениться от agent-screen, то тоже все ок, так как вышеобозначенный процесс завершается

**Comment by gl00m** [comment]
Как я решил для себя эту проблемку:
cp /usr/bin/screen-4.0.3 /config/screen-custom
и подключаюсь к agent-screen'у через кастомный скрин)
В процессе работы асика это все вообще не нужно, только когда захожу на него через ssh чтобы что-то посмотреть.

**Comment by Pasha49** [comment]
Баг проявляется, только если кто-то приаттачен к agent-screen. При стандартной работе бага нету.

**Comment by BuHeP** [comment]
999
