### ISSUE TITLE
Toddminer c1 “Putty” password

### ISSUE THREAD

**Issue by iccyeram** [minershive/hiveos-asic#10]
I try the follower password on putty to try to configure fan speed on my toddminer c1.

I try:

admin admin
root root
root admin
admin root

Not work

**Comment by j2h4u** [comment]
@HaloGenius please share

**Comment by j2h4u** [comment]
@iccyeram I was told that these credentials are restricted to developers only . Please try to ask Todd directly.

**Comment by HaloGenius** [comment]
We can prepare Hive ASIC client installation via firmware update but can't disclosure SSH password without the consent of the ASIC manufacturer
