### ISSUE TITLE
custom firmware for AntMiner E3

### ISSUE THREAD

**Issue by peterwillcn** [minershive/hiveos-asic#11]
I have some AntMiner E3 machines with custom firmware for 8 gigabytes of video memory to see how we can work together，Please leave your contact information and we'll talk about it in detail.
![E3](https://user-images.githubusercontent.com/323794/90968893-7ef83300-e524-11ea-94e7-3afdbec1b83b.png)

**Comment by j2h4u** [comment]
Hive OS Client does support Antminer E3 machines, please read [README](https://github.com/minershive/hiveos-asic/blob/master/README.md)

**Comment by peterwillcn** [comment]
> Hive OS Client does support Antminer E3 machines, please read [README](https://github.com/minershive/hiveos-asic/blob/master/README.md)

The Hive OS Client mining software supports 8 gigabytes of video memory with modified hardware?

**Comment by j2h4u** [comment]
> The Hive OS Client mining software supports 8 gigabytes of video memory with modified hardware?

The Client doesn't care for such subtleties. Put it bluntly, its only function is to collect the mining statistics data and to send it to the Hive OS dashboard. That's all.

**Comment by webspiderph** [comment]
> 
> 
> I have some AntMiner E3 machines with custom firmware for 8 gigabytes of video memory to see how we can work together，Please leave your contact information and we'll talk about it in detail.
> ![E3](https://user-images.githubusercontent.com/323794/90968893-7ef83300-e524-11ea-94e7-3afdbec1b83b.png)

you have firmware for E3 for 5gb

**Comment by wmany** [comment]
wmany@list.ru

**Comment by peterwillcn** [comment]
I have successfully fixed the firmware of Antminer E3 and the running power is about 160-200M（Memory chip frequency performance related）😄

**Comment by j2h4u** [comment]
This is relevant how? @peterwillcn please stop advertising
