### ISSUE TITLE
use wget if curl not found

### ISSUE THREAD

**Issue by pbrewton** [minershive/hiveos-asic#12]
file: hiveos-asic/hive/bin/selfupgrade
line: 1427

if/else still calls curl, if is_curl_available = false. Should be changed to wget.

**Comment by pbrewton** [comment]
issue created in error.

**Comment by j2h4u** [comment]
@pbrewton thanks for reporting. The issue could be in a dumb `is_curl_available` function. Have changed the code to be a little bit more smart:

commit https://github.com/minershive/hiveos-asic/commit/0ee1d30cbe334683b4fdfa93fc39deab93d607d2
