### ISSUE TITLE
Issue with connections

### ISSUE THREAD

**Issue by DreddZ** [minershive/hiveos-asic#13]
I am new to the miner community and just purchased a L3+ and upgraded the firmware to the Hiveon. I am not able to connect to any of my pools, and I am unable to connect to the SSH in order to reset the firmware.
I am sure there is a simple fix for what is going on but I am unable to figure it out with the research I have done.

**Comment by j2h4u** [comment]
@DreddZ Hello. I'm sorry that you've bumped into first-time issues. Please read [Hive Knowledge Base](https://hiveos.farm/hiveon-asic-firmware-L3+_L3++-L3+_L3++_installation/) or ask for an assisted support in our [dedicated telegram channel](https://t.me/hiveonasic_en).

That "Issues" thing on this very GitHub repo is for low-level technical issues. All these "steps to reproduce the issue", logs, linux commands, you know. The end-user support is not provided here.

**Comment by DreddZ** [comment]
Thanks
