### ISSUE TITLE
could not install client on S11 "System Upgrade failed"

### ISSUE THREAD

**Issue by subzero1234lx** [minershive/hiveos-asic#14]
when i want to update firmware with hive version it goes to error 
with btctools and web interface 
both of them leads to error 
please help

**Comment by j2h4u** [comment]
What's the date of your current firmware? Please give us a screenshot of web interface

**Comment by subzero1234lx** [comment]
you are write it seems about the date 
the date is  AUG 2019  

but i found that the main problem is that SSH port in my miner is closed and secured by signiture
and i can not open ssh terminal 
with puTTy when i open a ssh terminal it say  " connection refused" 

in bitmain support site there are 2 firmware for s11 
i try to upgrade to an old one  ( date 2018) but when try to upgrade, some error happen and it say  "Cannot Find Signature!!!"

also i try to do this with S11_hive.tar  but this does not work too and it did not upgrade with this file 

i think the main problem is ssh port is disabled

**Comment by subzero1234lx** [comment]
![Screenshot from 2021-03-22 14-52-03](https://user-images.githubusercontent.com/47768142/111976153-f58efa80-8b1e-11eb-83b7-b443bcb70bac.png)

![Screenshot from 2021-03-22 14-45-41](https://user-images.githubusercontent.com/47768142/111976297-1b1c0400-8b1f-11eb-837b-c7b58260782c.png)

**Comment by j2h4u** [comment]
Seems like this firmware is locked by Bitmain (signed fw + disabled ssh) and cannot be flashed with any kind of a custom firmware. I suggest to use Hiveon ASIC Hub: https://hiveos.farm/ASIC-Hub-about/

**Comment by subzero1234lx** [comment]
yes
tank u for your reply 
i will use hub
