### ISSUE TITLE
Missing WiFi drivers

### ISSUE THREAD

**Issue by JonZarate** [minershive/hiveos-asic#17]
Apologies in advance, I am new to this and not very knowledgeable on these topics.

I have a `Gigabyte Aorus GC-WBAX200 Dual-Band` and it's not working on HiveOs.

I found a comment [here](https://www.pbtech.com/product/NETGBM2400/Gigabyte-Aorus-GC-WBAX200-Dual-Band-AX3000--Blueto) about newest Linux kernels having it:

> Luckily it comes with a CD with its drivers on it, but if you dont have a CD drive, you will need to use a tethered internet connection (i.e connecting your phone in tethered mode) or Ethernet. With internet, the modem is automatically detected by windows and the drivers are installed automatically. Linux on the other hand will not support it out of the box unless you use the latest Ubuntu distro (Not LTS). To use with linux mint or other ubuntu based distros you will need to update the kernel which has the driver preinstalled for this card.

Is there anything I can do ? Can I somehow provide the update files and run it from the command line ?

Thanks.

**Comment by HaloGenius** [comment]
This is repository of Hive OS client for ASICs and there is no Wi-Fi drivers support. 
According to your question probably it concerns a client for the GPUs and in this case send your request/bug reports to bee@hiveos.farm
