### ISSUE TITLE
Do you support Bitmain Antminer S19j Pro?

### ISSUE THREAD

**Issue by zmaupin** [minershive/hiveos-asic#22]
I found one page (https://hiveon.com/ASIC-Hub-getting_started-add-devices/) that lists the S19j Pro as supported, but I do not see it here or under the Firmware list.

**Comment by j2h4u** [comment]
We don't have a custom Hiveon Firmware for Antminer Series 19 at this moment. Stay tuned!

Meanwhile, you could use ASIC Hub to connect your S19 farms to the Hive. Some customers told us that simplicity of operating ASIC miners under the Hub does win over complexity of a custom firmware
