### ISSUE TITLE
Problem Bitmain S17+

### ISSUE THREAD

**Issue by martinmdp** [minershive/hiveos-asic#23]
Hi, I have two Bitmain S17+, both was running fine (mining) with stock firmware, first I made a mistake and flash with HiveON S17"Pro" firmware, then the Asic show errors with the fans (fan not found)
Now I flash the Asic with the correct firmware (S17+), but I have the error "ERROR_SOC_INIT: soc init failed!", and can't start mining, the status show this errors:

 Chain #0 malfunction
 Chain #1 malfunction
 Chain #2 malfunction

I tested with different hiveON firmware versions for S17+ with no luck, also test differents overclocking profiles as suggested in the FAQ, but nothing helps, is there a possibility to back to Bitmain stock firmware?

thanks in advance

**Comment by j2h4u** [comment]
I'm sorry to hear that. Indeed we have that option:

![screenshot-20220122-0225](https://user-images.githubusercontent.com/39818683/158972343-abec7ffa-6f4a-4af1-b55e-9021e7afd85e.png)

**Comment by martinmdp** [comment]
Thanks but I have tested all the options but always get the same errors, can I flash via SD card with the Bitmain original firmware? I need the unsigned firmware of HiveOs for the S17+
