### ISSUE TITLE
Z9

### ISSUE THREAD

**Issue by Weiss1985** [minershive/hiveos-asic#3]
Привет всем.
Не могу поставить HiveOS на Z9.
Отключен ssh.

Miner Type | Antminer Z9
Hostname | Z9
Model | GNU/Linux
Hardware Version | 9.0.0.5
Kernel Version | Linux 4.6.0-xilinx-gff8137b-dirty #22 SMP PREEMPT Fri Dec 22 12:25:44 CST 2017
File System Version | Mon Nov 19 20:25:07 CST 2018
CGminer Version | 4.9.0

Пробовал прописать через Hostname как это делают для asic.tools
У них в инструкции написано так
`
Antminer|sleep 60 &&/usr/bin/curl --connect-timeout 30 -k -o /config/minerstat.sh https://asic.tools/sh/25298; chmod +x /config/minerstat.sh&&/bin/sh /config/minerstat.sh start&`

Прописывал вот так:
`Antminer|sleep 60 &&/usr/bin/curl --connect-timeout 30 -L --insecure -s -o /tmp/selfupgrade https://raw.githubusercontent.com/minershive/hiveos-asic/master/hive/bin/selfupgrade && FARM_HASH=hash_from_hiveos /bin/sh /tmp/selfupgrade&`

Помогите решить проблему.

**Comment by Pasha49** [comment]
Какая версия прошивки? Способ установки через hostname - это дырка в вебе от битмайна(вдруг в вашей версии прошивки дыра уже исправлена). На s9 только что проверил, работает. Вы предложили правильный вариант.  После прописывания, применения, и ожидания, на вкладке Overview не меняется hostname?
Или дайте доступ к вебу, пишите на почту 49{точка}pasha@gmail.com

**Comment by Weiss1985** [comment]
Hello to all.
I can not put HiveOS on Z9.
Ssh is disabled in firmware.

Miner Type | Antminer Z9
Hostname | Z9
Model | GNU/Linux
Hardware Version | 9.0.0.5
Kernel Version | Linux 4.6.0-xilinx-gff8137b-dirty #22 SMP PREEMPT Fri Dec 22 12:25:44 CST 2017
File System Version | Mon Nov 19 20:25:07 CST 2018
CGminer Version | 4.9.0

I tried to register via Hostname as they do it for asic.tools
They have written instructions:
`Antminer|sleep 60 &&/usr/bin/curl --connect-timeout 30 -k -o /config/minerstat.sh https://asic.tools/sh/25298; chmod +x /config/minerstat.sh&&/bin/sh /config/minerstat.sh start&`

I wrote it like this:
`Antminer|sleep 60 &&/usr/bin/curl --connect-timeout 30 -L --insecure -s -o /tmp/selfupgrade https://raw.githubusercontent.com/minershive/hiveos-asic/master/hive/bin/selfupgrade && FARM_HASH=hash_from_hiveos /bin/sh /tmp/selfupgrade&`

Pls help fix it

**Comment by Weiss1985** [comment]
> Какая версия прошивки? Способ установки через hostname - это дырка в вебе от битмайна(вдруг в вашей версии прошивки дыра уже исправлена). На s9 только что проверил, работает. Вы предложили правильный вариант. После прописывания, применения, и ожидания, на вкладке Overview не меняется hostname?
> Или дайте доступ к вебу, пишите на почту 49{точка}[pasha@gmail.com](mailto:pasha@gmail.com)

В hostname прописывается вся строчка. - `Antminer|sleep 60 &&/usr/bin/curl --connect-timeout 30 -L --insecure -s -o /tmp/selfupgrade https://raw.githubusercontent.com/minershive/hiveos-asic/master/hive/bin/selfupgrade && FARM_HASH=hash_from_hiveos /bin/sh /tmp/selfupgrade&`

**Comment by Pasha49** [comment]
Если ssh выключен так же, как и в новых s15, то можно попробовать через hostname включить ssh:
`Antminer|sleep 60 && /etc/init.d/dropbear start &`

**Comment by Weiss1985** [comment]
Неправельно выразился.
port 22: Connection refused

**Comment by Pasha49** [comment]
Да, он отклюен. Не помогает вариант с включением выше? Если нет, можно еще так попробовать:
`Antminer|sleep 60 && /usr/sbin/dropbear -r /config/dropbear_rsa_host_key -p 22 &`

**Comment by Weiss1985** [comment]
Не в какую..
не та не та команда не помогли

**Comment by Weiss1985** [comment]
Только сброс через SD.
Поставил прошивку Fuddware.
Возникла еще одна проблема. После того как хайв загружается выставляет дефолтный разгон.
А мне нужно на каждую плату выставить отдельный разгон.
Так же hiveos ставит только один пул, как прописать несколько?

**Comment by Pasha49** [comment]
Разгон ставится тот, что прописан в полетном листе. Вы можете выставить нудный разгон в веб интерфейсе асика, выполнить "miner config", скопировать параметры с разгоном из полученного конфига(кроме данных пулов). И вставить эти данные в настройки полетного листа в расширенные параметры майнера(если разгон одинаков на все устройства). Или вставить в расширенные параметры майнера на вкладке Тюнинга, если для каждого асика индивидуальный разгон.
Для нескольких пулов прописывать до трех, по пулу в каждой строке.

**Comment by Weiss1985** [comment]
Если Кто будет использовать прошивку Fuddware
Можно выставить разгон для каждой платы по отдельности.
Прописывается так:
"bitmain-freq": "725"
"bitmain-freq1": "725"
"bitmain-freq2": "725"
"bitmain-freq3": "725"
