### ISSUE TITLE
ssh channel is closed in the latest firmware of S9

### ISSUE THREAD

**Issue by gangm** [minershive/hiveos-asic#6]
The ssh channet is closed in the latest firmware of antminer S9, so how can i install the script? thanks

**Comment by MostafaJojo** [comment]
You should do this with sd card.
Put antminer s9 recovery sd card file in a sd card.
Remove out main board,
Chang j4 pin slot ( you can search this solution in antminer website)
Put sd in main board power on main board after  1 min green and red light blinking and now  power off main board change pin j4 to default slot.
Turn on main board and done.
And you can connect to ssh like as putty or...

**Comment by fire-walld** [comment]
what firmware should I choose,SD firmward is still block ssh with signature

**Comment by fire-walld** [comment]
> The ssh channet is closed in the latest firmware of antminer S9, so how can i install the script? thanks

use sshpass to unlock it

**Comment by j2h4u** [comment]
Resolved a long time ago.
