### ISSUE TITLE
T17 have error on selfupgrade

### ISSUE THREAD

**Issue by fire-walld** [minershive/hiveos-asic#8]
follow the option list,still have trouble in process **selfupgrade**

root@antMiner:/var/volatile/tmp# cd /tmp && curl -L --insecure -s -O https://raw
.githubusercontent.com/minershive/hiveos-asic/master/hive/bin/selfupgrade && sh
selfupgrade
Antminer T17
http://github.com/minershive/hiveos-asic/archive/v0.1-13.tar.gz
> Downloading http://github.com/minershive/hiveos-asic/archive/v0.1-13.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0   131    0     0     83      0 --:--:--  0:00:01 --:--:--  127k
  0     0    0 7586k    0     0   304k      0 --:--:--  0:00:24 --:--:--  232k
Install Antminer T17
selfupgrade: line 513: /etc/rcS.d/S69hive: not found
selfupgrade: .: line 515: can't open '/hive/bin/colors'

**Comment by j2h4u** [comment]
Resolved by numerous commits.
